### ISSUE TITLE
Problem Statement ready to be reviewed

### ISSUE THREAD

**Issue by caobo1994** [caobo1994/FourierSeries#1]
Hi Prof.

The problem statement is ready to be reviewed. Thanks!

Bo.

**Comment by smiths** [comment]
@caobo1994, I approve your problem statement.  Looks good.  There is some room for improvement in the future though.  It would be nice to have more context.  That is, tell the readers what the Fourier series is used for.  Also, some parts of the writing is a little informal.  For instance the last sentence could be made more professional.  :smile:
