### ISSUE TITLE
Multi-page - wrong refs

### ISSUE THREAD

**Issue by Ao99** [caobo1994/FourierSeries#10]
![image](https://user-images.githubusercontent.com/53056165/66706280-a83e1500-ecfe-11e9-8403-40e20caffd82.png)
On several pages, the references to calculations seam to display incorrectly, as shown in the picture.  Is it because more calculations need to be added in the future?

According to page 19, you might have deleted some calculations without change the refs.

**Comment by caobo1994** [comment]
It appears after I have made some modifications after version 0.9. I will correct them.

**Comment by caobo1994** [comment]
Updated in commit c1b3f87
