### ISSUE TITLE
Page ii - Table of Symbols

### ISSUE THREAD

**Issue by Ao99** [caobo1994/FourierSeries#11]
You might want to add more symbols mentioned in this document to make this table more complete and detailed.

Some examples: 't, π, ai, m1, m2' might need their own rows. 'A, B, App, Amp, in, out, tol' might need to be mentioned here.

**Comment by caobo1994** [comment]
I accept the advice on 'A, B, tol'. 

'in' and 'out' are self-explanatory enough.

'App' and 'Amp' is the focus of some dd, and it seems redundant to put them in table of symbols.

As to 't, \pi', readers surely understand what they means, and 'ai, m1, m2' has no actual meanings, which means they are purely placeholders.

**Comment by caobo1994** [comment]
Updated in 8c7fc2d.

'A, B, tol, Amp, App' added. 'Amp' and 'App' can be removed easily if they are deemed redundant in the future.

**Comment by smiths** [comment]
I like `Amp` and `App` in your table of symbols.  You really can't err on the side of defining too many symbols.  They really should all be defined for completeness.
