### ISSUE TITLE
Page 17 - output

### ISSUE THREAD

**Issue by Ao99** [caobo1994/FourierSeries#12]
![image](https://user-images.githubusercontent.com/53056165/66706516-a88bdf80-ed01-11e9-890b-a0b4c90b07b5.png)

The first output O1 looks more like a requirement. You might want to specify what kinds of outputs can be expected from this library.

You've written a very detailed Goal Statement, so you might be able to ref the GS to here to avoid redundant descriptions.

**Comment by caobo1994** [comment]
I will edit accordingly.

**Comment by caobo1994** [comment]
Updated in a87d24c

**Comment by smiths** [comment]
@caobo1994, as I mentioned in my review of your CA (commit b41252a), documenting your CA as an SRS makes more sense.  The SRS template does not have an output heading, so you can remove this.  Your requirement will be captured by your requirements.
