### ISSUE TITLE
Multi page - use of symbol

### ISSUE THREAD

**Issue by Ao99** [caobo1994/FourierSeries#13]
![image](https://user-images.githubusercontent.com/53056165/66706603-b857f380-ed02-11e9-9065-1af7d802eadd.png)
Since these two symbols have been defined as the above picture shown, you might want to carefully consider whether or not they should always be used.
![image](https://user-images.githubusercontent.com/53056165/66706629-1be22100-ed03-11e9-86a2-debc4e05c224.png)
An example is shown in the second pic, GS3 uses the symbols but GS2 doesn't. This may cause poor consistency.

**Comment by caobo1994** [comment]
I know. I usually use CFSf and CFSg when they appear in binary operations (or in pairs).

**Comment by caobo1994** [comment]
Updated in d937e85
