### ISSUE TITLE
More detail for conducting tests 5.1.1 - 5.1.4

### ISSUE THREAD

**Issue by peter-michalski** [caobo1994/FourierSeries#19]
How are the inputs placed into the system for testing purposes?
How are the outputs retrieved?
Formats etc.

If someone else was told to conduct the test, what specific details would you give?

**Comment by caobo1994** [comment]
Just call the functions in my library with the inputs, and receive the output as the return value of the function.

I am writing a library, not a program. Detail of how to call functions in this library (interface of library) is the task of the following libraries.


Sent from Mail for Windows 10

From: peter-michalski
Sent: Tuesday, October 29, 2019 18:13
To: caobo1994/FourierSeries
Cc: Subscribed
Subject: [caobo1994/FourierSeries] More detail for conducting tests (#19)

How are the inputs placed into the system for testing purposes?
How are the outputs retrieved?
Formats etc.
If someone else was told to conduct the test, what specific details would you give?

**Comment by peter-michalski** [comment]
>Just call the functions in my library with the inputs, and receive the output as the return value of the function.

Will the user need to navigate to the functions? If so, are there instructions on getting to the functions? 
Or are the functions automatically selected once you enter the module?

**Comment by caobo1994** [comment]
Navigate? No, no, no. We are not using any GUIs. The users just type the name of the functions in their code, together with parameters, and when they execute the code, the function in our library is executed, and the output is returned by this function.

Sent from Mail for Windows 10

**Comment by caobo1994** [comment]
Sorry that I have to close this issue right now.
