### ISSUE TITLE
User responsibilities 

### ISSUE THREAD

**Issue by deemaalomair1** [caobo1994/FourierSeries#2]
Hello Bo Cao, 

I read your CA document. In section 4.1 (User responsibilities) 
I do not really think point number two is user User responsibility. It like more system related responsibility. 

Attached picture of the section.

![Screen Shot 2019-10-09 at 10 58 07 AM](https://user-images.githubusercontent.com/45468077/66496225-994e2d00-ea88-11e9-862b-6697dd8d8462.png)

**Comment by caobo1994** [comment]
I mean that the user shall allocate space, and provide their address to the library, so that the library can store the output in the space.

Better wording (I think) is added.
