### ISSUE TITLE
Clarify test output 

### ISSUE THREAD

**Issue by peter-michalski** [caobo1994/FourierSeries#21]
The way that the test output is written in your test cases may be unclear.
For example 5.1.1 (2) has |Amp(CFSf ) − 3.0| ≤ epsilon

Is this actually the output? The output seems like it would simply be 'True'

The |Amp(CFSf ) − 3.0| ≤ epsilon might be better if it was in the derivation section.

**Comment by caobo1994** [comment]
Yes. I intend to make it the test output.

Sent from Mail for Windows 10

From: peter-michalski
Sent: Tuesday, October 29, 2019 18:31
To: caobo1994/FourierSeries
Cc: Subscribed
Subject: [caobo1994/FourierSeries] Clarify test output (#21)

The way that the test output is written in your test cases may be unclear.
For example 5.1.1 (2) has |Amp(CFSf ) − 3.0| ≤ epsilon
Is this actually the output? The output seems like it would simply be 'True'
The |Amp(CFSf ) − 3.0| ≤ epsilon might be better if it was in the derivation section.

**Comment by peter-michalski** [comment]
The output will literally be '|Amp(CFSf ) − 3.0|' AND 'True/False'? 

The screen will show '|Amp(CFSf ) − 3.0|'?

**Comment by caobo1994** [comment]
The output is the evaluated value of expression |Amp(CFSf ) − 3.0|, which could be ‘True’ or ‘False’ (Boolean values, not strings). The right answer is ‘True’, indicating a passed test.

Sent from Mail for Windows 10

**Comment by caobo1994** [comment]
Clarified in 8965584
