### ISSUE TITLE
5.2.1 linking to NFRs

### ISSUE THREAD

**Issue by peter-michalski** [caobo1994/FourierSeries#23]
Hi, 

Is the speed test designed to cover NFR2 NFR3, NFR4, NFR6? 
I ask because you have IM1, IM3, IM4, IM5, IM8, IM9 mentioned at the top of this test. 

However the NFR for some of these (IM1 IM5) mentions O(n^2) not linear time. 

Should the test be different for these IM's since linear time is not of interest according to the CA?

**Comment by caobo1994** [comment]
Well, for each test of speed, the test result shall match the NFR's speed
rule. I only show one test as example, which happens to require linear time.

peter-michalski <notifications@github.com> 于 2019年10月29日周二 20:00写道：
