### ISSUE TITLE
input related testing 

### ISSUE THREAD

**Issue by deemaalomair1** [caobo1994/FourierSeries#28]
hello, 

i did not see any test about the the input and input format or constrains .. are you assume that this is user responsibilities ? i think if this is the case you need to mention that somewhere in the document.

**Comment by caobo1994** [comment]
Yes. Some of them are user responsibilities, some functions have actually no constraints, and I will add a sentence describing the remaining ones.

Sent from Mail for Windows 10

From: deemaalomair1
Sent: Thursday, October 31, 2019 12:32
To: caobo1994/FourierSeries
Cc: Subscribed
Subject: [caobo1994/FourierSeries] input related testing (#28)

hello,
i did not see any test about the the input and input format or constrains .. are you assume that this is user responsibilities ? i think if this is the case you need to mention that somewhere in the document.

**Comment by caobo1994** [comment]
Changes in commit 485ca2e
