### ISSUE TITLE
Domain Expert Code: following functions.

### ISSUE THREAD

**Issue by caobo1994** [caobo1994/FourierSeries#31]
I have chosen a set of functions for you to implement.
The functions are
* FunctionValue
* Addition
* Subtraction
* Amplitude
* Power
* ToleratedEquality

You can choose some of them to implement. It is recommended that you choose at least 3 of them.

You should implement each function in a separate c++ header file. A template has been provided in src/Template.hpp.

**Comment by smiths** [comment]
@caobo1994, I'm sorry, but I don't believe that @deemaalomair1 will be able to complete this.  She is currently on maternity leave.  @deemaalomair1, I will exclude this requirement for your grade calculation.

**Comment by caobo1994** [comment]
Sorry for not knowing this. I have implemented a backup version by myself, and the backup version works fine.

**Comment by smiths** [comment]
No problem @caobo1994.  @deemaalomair1 and I thought she might be able to get to this task, but it didn't work out.  I'm glad that you implemented it yourself.  Thank you.
