### ISSUE TITLE
Data Definition 8 

### ISSUE THREAD

**Issue by deemaalomair1** [caobo1994/FourierSeries#4]
Hello ,
In data definition section , DD8 which talks about function of CFS's. I did not get the idea of the function ? it may be better if you describe it more or in different way.  

![Screen Shot 2019-10-09 at 11 45 10 AM](https://user-images.githubusercontent.com/45468077/66497340-57be8180-ea8a-11e9-8e0e-1084a1e258b9.png)

**Comment by caobo1994** [comment]
I messed up its theory with its definition. Revised.

**Comment by smiths** [comment]
@caobo1994, to help the reader understand your document, I made the suggestion in my comments that you include the type signature with your functions.
