### ISSUE TITLE
CFS's operations

### ISSUE THREAD

**Issue by deemaalomair1** [caobo1994/FourierSeries#5]
hello, 

In your CA document you added CFS's operations as instance models, data definition and theoretical model. from my point of view i think they are more likely to be instance model. Moreover, your description of the operations in the theoretical models is about how to get the data needed to do the operation. so i think it should be under data definition section and  maybe if you change the title of them it will be more clear.  like "get data needed for addition".

**Comment by caobo1994** [comment]
My intention is to define an operation, develop the theory to calculate its resulted CFS (essentially the coeffs in it), and treat this operation as an instance (users can call each instance/operation independently).

I will think of better ways to organize.
